# Generated by Django 3.2.20 on 2023-07-12 11:55

import cloudinary.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Van',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('size', models.CharField(choices=[('SMALL', 'Small'), ('MEDIUM', 'Medium'), ('LARGE', 'Large')], max_length=75)),
                ('location', models.CharField(choices=[('LONDON', 'London'), ('MANCHESTER', 'Manchester'), ('BIRMINGHAM', 'Birmingham'), ('LEEDS', 'Leeds'), ('GLASGOW', 'Glasgow'), ('SOUTHAMPTON', 'Southampton'), ('LIVERPOOL', 'Liverpool'), ('NEWCASTLE', 'Newcastle'), ('SHEFFIELD', 'Sheffield'), ('BRIGHTON', 'Brighton'), ('CARDIFF', 'Cardiff')], max_length=75)),
                ('county', models.CharField(choices=[('GREATER LONDON', 'Greater London'), ('GREATER MANCHESTER', 'Greater Manchester'), ('WEST MIDLANDS', 'West Midlands'), ('WEST YORKSHIRE', 'West Yorkshire'), ('GLASGOW CITY', 'Glasgow City'), ('HAMPSHIRE', 'Hampshire'), ('MERSEYSIDE', 'Merseyside'), ('TYNE AND_WARE', 'Tyne & Ware'), ('SOUTH YORKSHIRE', 'South Yorkshire'), ('EAST SUSSEX', 'East Sussex'), ('CARDIFF', 'Cardiff')], max_length=75)),
                ('crew', models.IntegerField(default=1)),
                ('suitable_for', models.TextField(max_length=200)),
                ('load_area_width', models.IntegerField(verbose_name='Load Area Width in metres')),
                ('load_area_height', models.IntegerField(verbose_name='Load Area Height in metres')),
                ('load_area_length', models.IntegerField(verbose_name='Load Area Length in metres')),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('date_added', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_live', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
    ]
