# Generated by Django 3.2.20 on 2023-07-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoomoov_app', '0002_auto_20230712_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='van',
            name='county',
            field=models.CharField(choices=[('CARDIFF', 'Cardiff'), ('EAST SUSSEX', 'East Sussex'), ('GLASGOW CITY', 'Glasgow City'), ('GREATER LONDON', 'Greater London'), ('GREATER MANCHESTER', 'Greater Manchester'), ('HAMPSHIRE', 'Hampshire'), ('MERSEYSIDE', 'Merseyside'), ('SOUTH YORKSHIRE', 'South Yorkshire'), ('TYNE AND_WARE', 'Tyne & Ware'), ('WEST MIDLANDS', 'West Midlands'), ('WEST YORKSHIRE', 'West Yorkshire')], max_length=75),
        ),
        migrations.AlterField(
            model_name='van',
            name='location',
            field=models.CharField(choices=[('BIRMINGHAM', 'Birmingham'), ('BRIGHTON', 'Brighton'), ('CARDIFF', 'Cardiff'), ('GLASGOW', 'Glasgow'), ('LEEDS', 'Leeds'), ('LIVERPOOL', 'Liverpool'), ('LONDON', 'London'), ('MANCHESTER', 'Manchester'), ('NEWCASTLE', 'Newcastle'), ('SHEFFIELD', 'Sheffield'), ('SOUTHAMPTON', 'Southampton')], max_length=75),
        ),
        migrations.AlterField(
            model_name='van',
            name='slug',
            field=models.SlugField(help_text='Example: your_van_name', max_length=200, unique=True, verbose_name='Unique Url Slug'),
        ),
    ]
