# Generated by Django 3.2.20 on 2023-07-18 10:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yoomoov_app', '0004_van_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(blank=True, editable=False, max_length=200, unique=True)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('date_required', models.DateField()),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('date_updated', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed')], max_length=25)),
                ('van', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='yoomoov_app.van')),
            ],
            options={
                'ordering': ['-date_required'],
            },
        ),
    ]
