# Generated by Django 3.2.20 on 2023-07-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoomoov_app', '0005_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=6, verbose_name='Total Price'),
        ),
        migrations.AddField(
            model_name='booking',
            name='van_county',
            field=models.CharField(choices=[('Cardiff', 'Cardiff'), ('East Sussex', 'East Sussex'), ('Glasgow City', 'Glasgow City'), ('Greater London', 'Greater London'), ('Greater Manchester', 'Greater Manchester'), ('Hampshire', 'Hampshire'), ('Merseyside', 'Merseyside'), ('South Yorkshire', 'South Yorkshire'), ('Tyne & Ware', 'Tyne & Ware'), ('West Midlands', 'West Midlands'), ('West Yorkshire', 'West Yorkshire')], default='Cardiff', max_length=75),
        ),
        migrations.AddField(
            model_name='booking',
            name='van_location',
            field=models.CharField(choices=[('Birmingham', 'Birmingham'), ('Brighton', 'Brighton'), ('Cardiff', 'Cardiff'), ('Glasgow', 'Glasgow'), ('Leeds', 'Leeds'), ('Liverpool', 'Liverpool'), ('London', 'London'), ('Manchester', 'Manchester'), ('Newcastle', 'Newcastle'), ('Sheffield', 'Sheffield'), ('Southampton', 'Southampton')], default='Birmingham', max_length=75),
        ),
        migrations.AddField(
            model_name='booking',
            name='van_size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Small', max_length=75),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Completed', 'Completed')], default='Pending', max_length=25),
        ),
        migrations.AlterField(
            model_name='van',
            name='county',
            field=models.CharField(choices=[('Cardiff', 'Cardiff'), ('East Sussex', 'East Sussex'), ('Glasgow City', 'Glasgow City'), ('Greater London', 'Greater London'), ('Greater Manchester', 'Greater Manchester'), ('Hampshire', 'Hampshire'), ('Merseyside', 'Merseyside'), ('South Yorkshire', 'South Yorkshire'), ('Tyne & Ware', 'Tyne & Ware'), ('West Midlands', 'West Midlands'), ('West Yorkshire', 'West Yorkshire')], max_length=75),
        ),
        migrations.AlterField(
            model_name='van',
            name='location',
            field=models.CharField(choices=[('Birmingham', 'Birmingham'), ('Brighton', 'Brighton'), ('Cardiff', 'Cardiff'), ('Glasgow', 'Glasgow'), ('Leeds', 'Leeds'), ('Liverpool', 'Liverpool'), ('London', 'London'), ('Manchester', 'Manchester'), ('Newcastle', 'Newcastle'), ('Sheffield', 'Sheffield'), ('Southampton', 'Southampton')], max_length=75),
        ),
        migrations.AlterField(
            model_name='van',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], max_length=75),
        ),
    ]
