# Generated by Django 3.2.20 on 2023-07-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoomoov_app', '0006_auto_20230718_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_number',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
