# Generated by Django 3.2.20 on 2023-07-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoomoov_app', '0008_alter_booking_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user_id',
            field=models.IntegerField(blank=True, default='0'),
        ),
    ]
