# Generated by Django 3.2.20 on 2023-07-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoomoov_app', '0009_booking_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='van_name',
            field=models.CharField(default='Enter name of van', max_length=250),
        ),
    ]
