# Generated by Django 3.2.20 on 2023-07-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoomoov_app', '0013_alter_feedback_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_approved_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_completed_notified',
            field=models.BooleanField(default=False),
        ),
    ]
