# Generated by Django 3.2.20 on 2023-07-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoomoov_app', '0014_auto_20230727_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_approved_notified',
            field=models.BooleanField(default=False),
        ),
    ]
